### ISSUE TITLE
This theme with a compositor

### ISSUE THREAD

**Issue by maxresd3fault** [luigifab/human-theme#22]
Hey I love this theme, and it's super awesome you have been maintaining it. I've been using it on MATE and it's been working great. However, I notice in your instructions in the readme you say to turn off the mate compositor, and I see why. I do notice a few minor problems with it on, however turning it off just isn't really an option for me. With it off there's too much screen tearing mostly in programs like Firefox. So I am wondering if you are planning on ever patching the theme to work fully with compositors.

The only issues I notice with the compositor on are:

- The brightness and volume popups look broken
- When using the MATE Screenshot tool with "Select area to grab" the selection is just gray and not transparent, meaning you can't see what you're screenshoting.

And again these problems aren't here with the compositor off, but like I said turning it off just causes more problems than that for me with other programs unrelated to the theme.

**Comment by luigifab** [comment]
Thanks! Yes I ask to turn off the mate compositor, mainly because I don't use it,
and because I dislike the shadow behind the windows.

![image](https://github.com/luigifab/human-theme/assets/31816829/d436e52b-2f05-4171-9f8a-227a50f6a029)

You are right for the volume popup:

![image](https://github.com/luigifab/human-theme/assets/31816829/4f3da9a1-ee12-49ae-99d5-66382c5a9dd3)

---

I'm working on the next release next month, but for now it doesn't fix these problems.
There are probably some new CSS classes, I don't know.

**Comment by maxresd3fault** [comment]
In that case I would be curious to hear what you do with Firefox then and if you have the same screen tearing issues without the compositor. I read that it used to be possible to enable OpenGL acceleration in Firefox standalone but it seems that doesn't work in the latest versions.

**Comment by luigifab** [comment]
I have no problems with Firefox without compositor.
What problems do you have? Do you have a screenshot?

I only have a black border (but when I resize the dialog, it seems to be the background, not sure) for download dialog (and also the colored rectangle):

![image](https://github.com/luigifab/human-theme/assets/31816829/105546bd-4208-4fec-80a0-adefd78de29d)

**Comment by luigifab** [comment]
Found! (via [788](https://github.com/mate-desktop/marco/issues/788)).

The border comes from the following CSS code, the border width apply only when compositor is enabled.
https://github.com/luigifab/human-theme/blob/9fa209d988e08e9fe2e87b2ca6fe0c9cb0ed4da8/src/human-theme/gtk-3.0/mate.css#L295-L299

So for the next release next month solution is:
```css
/* --- multimedia osd --- */
/* @see https://github.com/mate-desktop/mate-settings-daemon/blob/e57d532ac69fc3f6f5a34d9ce648bbdfb6a81185/plugins/common/msd-osd-window.c#L215 */

.osd {
	/* with compositor: all applies to multimedia and alttab osd (for window and progressbar) */
	/* without compositor: only border-radius and border-color for multimedia osd */
	border: 1px solid @nb_border;
	border-radius: 10px;
	background: @theme_bg;
}

.osd .progressbar {
	/* with compositor: multimedia osd progressbar */
	border: 0;
	background: @theme_selected_bg;
}

.osd.msd-osd-window-solid {
	/* without compositor: multimedia osd window */
	border-radius: 0;
}

.osd.msd-osd-window-solid > box {
	/* without compositor: multimedia osd window background and background-border */
	background: @theme_bg;
	box-shadow:
		0 -11px @theme_bg, /* top */
		11px  0 @theme_bg, /* right */
		0  11px @theme_bg, /* bottom */
		-11px 0 @theme_bg, /* left */
		-11px -11px @theme_bg, /* top left */
		 11px -11px @theme_bg, /* top right */
		 11px  11px @theme_bg, /* bottom right */
		-11px  11px @theme_bg  /* bottom left */;
}

/* --- tabwin alttab alt-tab osd (marco) v1.28.2+ --- */
/* @see https://github.com/mate-desktop/marco/pull/789 */

frame.mate-tabwin > border {
	/* with or without compositor */
	/* without compositor avoid white background when popup is displayed over geany or terminal windows */
	border-radius: 0;
}
```

![Image](https://github.com/user-attachments/assets/463fd119-809f-46ef-aec4-a9b4b09425d9)

---

This does not fix problems with Firefox 136:

![Image](https://github.com/user-attachments/assets/fac9c7d3-df45-4ccd-8566-bcede6f0fb98)

**Comment by luigifab** [comment]
For mate-screenshot "select area to grab":

https://github.com/luigifab/human-theme/blob/9fa209d988e08e9fe2e87b2ca6fe0c9cb0ed4da8/src/human-theme/gtk-3.0/base.css#L40-L50

Solution is:
```css
XfdesktopIconView.view .rubberband,
rubberband,
.rubberband,
.background.rubberband {
	border-color: alpha(@theme_selected_bg, 0.8);
	background: alpha(@theme_selected_bg, 0.4);
}

.background {
	color: @theme_fg;
	background: @theme_bg;
}
```
